Repository TypeCobolTeam/TypeCobol, pull requests merged in 2019-03, with the labels that each got.

#1308 WI #1301 Optimize symbol table
  TypeCobol.Test/Parser/Programs/TypeCobol/CircularReferenceType.rdzMix.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/CircularReferenceType.rdzPGM.txt
  TypeCobol/Compiler/CodeModel/SymbolTable.cs
  TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
  TypeCobol/Compiler/Diagnostics/TypeCobolLinker.cs
Labels: Enhancement, Performance, User Visible

#1321 WI #1019 Generate TypeDef declaration with a body inside a COPY file.
  Codegen/src/Generators/DefaultGenerator.cs
  Codegen/src/Generators/LinearNodeSourceCodeMapper.cs
  Codegen/src/Nodes/TypedDataNode.cs
  Codegen/test/Codegen.Test.csproj
  Codegen/test/TestTypeCobolCodegen.cs
  Codegen/test/resources/input/TypeCobol/TypedefCopys/MyCopyA.cpy
  Codegen/test/resources/input/TypeCobol/TypedefCopys/MyCopyB.cpy
  Codegen/test/resources/input/TypeCobol/TypedefCopys/TypedefBodyInsideCopy.rdz.tcbl
  Codegen/test/resources/output/TypeCobol/TypedefCopys/TypedefBodyInsideCopy.rdz.tcbl
  TypeCobol/Compiler/Nodes/Node.cs
Labels: Codegen

#1293 Fix #1292 ASTVisitor now visit parameters of FunctionDeclaration
  TypeCobol.Test/Parser/Programs/TypeCobol/FunctionsDeclaration.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall.rdzPGM.txt
  TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
  TypeCobol/Compiler/Nodes/Procedure.cs
Labels: Bug, User Visible

#1314 WI #1301 #1294 optimize symbol table part2
  Codegen/src/Actions/Qualifier.cs
  TypeCobol.Test/Parser/Programs/Cobol2002/DependingOn2002.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol2002/DependingOn2002.rdzMix.txt
  TypeCobol/Compiler/CodeModel/SymbolTable.cs
  TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
  TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
  TypeCobol/Compiler/Nodes/Attributes.cs
  TypeCobol/Compiler/Nodes/Data.cs
  TypeCobol/Compiler/Nodes/Node.cs
  TypeCobol/Compiler/Nodes/Procedure.cs
Labels: Enhancement, Performance

#1315 WI #1009 Specific data type for level88
  Codegen/test/resources/input/TypeCobol/ProcedureCall-Public.rdz.tcbl
  Codegen/test/resources/output/TypeCobol/ProcedureCall-Public.rdz.tcbl
  TypeCobol.LanguageServer.Test/LSRTests/DisplayCompletion/input/DisplayCompletion.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/IfCompletion/input/IfCompletion.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionPotentialChildrenWithNoName/input/ProcedureCompletionPotentialChildrenWithNoName.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/SetToAddressOfCompletion/input/SetToAddressOfCompletion.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/VariableQualifiedNameCompletion2/input/VaraibleQualifiedNameCompletion2.tlsp
  TypeCobol.Test/Parser/Documentation/DocumentationTypeDefs.rdz.json
  TypeCobol.Test/Parser/Documentation/DocumentationTypeDefs.rdzDoc.txt
  TypeCobol.Test/Parser/EILegacy/AutoRemarks.rdzPGM.txt
  TypeCobol.Test/Parser/EILegacy/Suffix.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol2002/LevelChecker.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/Condition.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/FileControlPGM.Txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/Redefines.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/SelectFilePGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/DoubleColonPGM.txt
  TypeCobol/Compiler/CodeElements/Entry/DataDescriptionEntry.cs
  TypeCobol/Compiler/CodeElements/Entry/DataType.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: Enhancement, Performance
