Repository TypeCobolTeam/TypeCobol, pull requests merged in 2020-01, with the labels that each got.

#1537 WI #1456 Implement LOC option of Allocate statement
  TypeCobol.Test/Parser/CodeElements/ALLOCATE.cbl
  TypeCobol.Test/Parser/CodeElements/ALLOCATE.txt
  TypeCobol/AntlrGrammar/Cobol2002CodeElements.g4
  TypeCobol/Compiler/CodeElements/Statement/AllocateStatement.cs
  TypeCobol/Compiler/Parser/CodeElementBuilder/CobolStatementsBuilder.cs
Labels: 🔍 Ready for Review

#1568 WI 1513 log file path option
  CLI/src/CLI.cs
  CLI/src/Daemon.cs
  TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
Labels: ✅ Approved

#1614 Close #1613 Deactivate label Approved of Trafico
  .github/trafico.yml
Labels: 🔍 Ready for Review

#1599 WI #1591 Fix exception when a blank line is inserted at the end of co…
  TypeCobol.LanguageServer.Test/LSRTests/AddMultipleLinesWithEmptyLineInside/input/AddMultipleLinesWithEmptyLineInside.tlsp
  TypeCobol.LanguageServer/TypeCobolServer.cs
Labels: To merge, 🔍 Ready for Review

#1611 WI #1254 Remove exception and display error message when using variab…
  TypeCobol.Test/Parser/Programs/TypeCobol/MoveAll.rdz.tcbl
  TypeCobol.Test/Parser/Programs/TypeCobol/MoveAll.rdzMix.txt
  TypeCobol/Compiler/Parser/CodeElementBuilder/CobolWordsBuilder.cs
Labels: To merge, 🔍 Ready for Review

#1615 WI #1287 Fix completion on external procedure with no arguments
  TypeCobol.LanguageServer.Test/LSRTest.cs
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionNoParam/input/ProcedureCompletionNoParam.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionNoParam/output_expected/ProcedureCompletionNoParam.rlsp
  TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
  TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
Labels: To merge

#1596 WI #783 Complete after special keyword space quote
  TypeCobol.LanguageServer.Test/LSRTests/MoveZeroSpaceCompletion/input/MoveZeroSpaceCompletion.tlsp
  TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
Labels: To merge, 🔍 Ready for Review

#1633 WI #1260 Add unit test for GlobalStorage visibility
  TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageVisibility.rdz.tcbl
  TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageVisibility.rdzMix.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/Typedef-public.rdz.tcbl
Labels: 🔍 Ready for Review

#1630 WI #1627 Align csproj configuration properties and make use of Common…
  CLI/test/CLI.Test.csproj
  Codegen/test/Codegen.Test.csproj
  TypeCobol.Test/TypeCobol.Test.csproj
  TypeCobol.Transform.Test/TypeCobol.Transform.Test.csproj
  TypeCobol.Transform/TypeCobol.Transform.csproj
  TypeCobol/Common.props
  TypeCobol/TypeCobol.ruleset
Labels: To merge, 🔍 Ready for Review

#1603 CLI : improve multiple files parsing
  CLI/src/CLI.cs
  CLI/src/Writer.cs
  CLI/test/CLI.Test.csproj
  CLI/test/CLITest.cs
  CLI/test/ressources/checkMissingCopies/output_expected/MissingCopy.txt
  CLI/test/ressources/checkMissingCopies/output_expected/error.txt
  CLI/test/ressources/cross_compilation_sources/output_expected/error.txt
  CLI/test/ressources/dependenciesNotLoadedInCorrectOrder_2/input/DVZTEST1.rdz.tcbl
  CLI/test/ressources/empty_dependency_folder/output_expected/error.txt
  CLI/test/ressources/mass_generation_all_programs_ok/CLIArguments.txt
  CLI/test/ressources/mass_generation_all_programs_ok/input/DVZZPGM1.tcbl
  CLI/test/ressources/mass_generation_all_programs_ok/input/DVZZPGM2.tcbl
  CLI/test/ressources/mass_generation_all_programs_ok/input/DVZZPGM3.tcbl
  CLI/test/ressources/mass_generation_all_programs_ok/output_expected/DVZZPGM1.cbl
  CLI/test/ressources/mass_generation_all_programs_ok/output_expected/DVZZPGM2.cbl
  CLI/test/ressources/mass_generation_all_programs_ok/output_expected/DVZZPGM3.cbl
  CLI/test/ressources/mass_generation_all_programs_ok/output_expected/error.txt
  CLI/test/ressources/mass_generation_dependent_programs_1/CLIArguments.txt
  CLI/test/ressources/mass_generation_dependent_programs_1/input/DVZZPGM1.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_1/input/DVZZPGM2.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_1/input/DVZZPGM3.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_1/output_expected/DVZZPGM1.cbl
  CLI/test/ressources/mass_generation_dependent_programs_1/output_expected/DVZZPGM2.cbl
  CLI/test/ressources/mass_generation_dependent_programs_1/output_expected/DVZZPGM3.cbl
  CLI/test/ressources/mass_generation_dependent_programs_1/output_expected/error.txt
  CLI/test/ressources/mass_generation_dependent_programs_2/CLIArguments.txt
  CLI/test/ressources/mass_generation_dependent_programs_2/input/DVZZPGM1.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_2/input/DVZZPGM2.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_2/input/DVZZPGM3.tcbl
  CLI/test/ressources/mass_generation_dependent_programs_2/output_expected/DVZZPGM3.cbl
  CLI/test/ressources/mass_generation_dependent_programs_2/output_expected/error.txt
  CLI/test/ressources/mass_generation_one_program_is_ko/CLIArguments.txt
  CLI/test/ressources/mass_generation_one_program_is_ko/input/DVZZPGM1.tcbl
  CLI/test/ressources/mass_generation_one_program_is_ko/input/DVZZPGM2.tcbl
  CLI/test/ressources/mass_generation_one_program_is_ko/input/DVZZPGM3.tcbl
  CLI/test/ressources/mass_generation_one_program_is_ko/output_expected/DVZZPGM1.cbl
  CLI/test/ressources/mass_generation_one_program_is_ko/output_expected/DVZZPGM3.cbl
  CLI/test/ressources/mass_generation_one_program_is_ko/output_expected/error.txt
  TypeCobol/Tools/APIHelpers/Helpers.cs
Labels: To merge

#1638 WI #1262 Create Symbol and Type base classes
  TypeCobol.Test/Types/PictureStringUnitTest.cs
  TypeCobol/Compiler/Nodes/Data.cs
  TypeCobol/Compiler/Nodes/SemanticData.cs
  TypeCobol/Compiler/Symbols/Symbol.cs
  TypeCobol/Compiler/Types/PictureType.cs
  TypeCobol/Compiler/Types/Type.cs
Labels: To merge, 🔍 Ready for Review

#1605 WI #1576 Modify completion on indexed list of typed element to show i…
  TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterDotFromTypedDataDef/input/CompletionAfterDotFromTypedDataDef.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterDotFromTypedDataDef/input/CustomDependencies/CustomDep.tcbl
  TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
Labels: Bug, Language Server Protocol, To merge, User Visible

#1604 WI #1594 Display error when character outside editable range is detected
  TypeCobol.Test/Parser/Programs/Cobol85/CharOutsideEditableRange.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/CharOutsideEditableRange.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine1.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine1.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine2.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine2.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine3.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine3.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine4.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine4.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine5.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine5.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine6.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine6.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine7.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine7.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine8.rdz.tcbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationLine/ContinuationLine8.rdzMix.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ContinuationLine.rdz.tcbl
  TypeCobol.Test/Parser/Programs/TypeCobol/ContinuationLine.rdzPGM.txt
  TypeCobol.Test/Parser/Scanner/ResultFiles/AlphanumericLiterals-continuations.txt
  TypeCobol.Test/Parser/Scanner/ResultFiles/AlphanumericLiterals1.txt
  TypeCobol/Compiler/Diagnostics/MessageCode.cs
  TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
  TypeCobol/Compiler/Scanner/Scanner.cs
Labels: To merge, 🔍 Ready for Review

#1600 1588 review equals get hash code
  TypeCobol.LanguageServer/VsCodeProtocol/Signature Help/SignatureInformation.cs
  TypeCobol/Compiler/CodeElements/Entry/DataType.cs
  TypeCobol/Compiler/CodeElements/Expressions/StorageArea.cs
  TypeCobol/Compiler/CodeElements/Expressions/SymbolName.cs
  TypeCobol/Compiler/CodeElements/Header/FunctionDeclarationHeader.cs
  TypeCobol/Compiler/Nodes/ParametersProfileNode.cs
  TypeCobol/Compiler/Scanner/Token.cs
  TypeCobol/Compiler/Source/GapSourceText.cs
  TypeCobol/Compiler/Source/StringSourceText.cs
  TypeCobol/TypeCobol.ruleset
Labels: Enhancement, To merge, 🔍 Ready for Review
