Repository TypeCobolTeam/TypeCobol, pull requests merged in 2020-03, with the labels that each got.

#1664 WI #1660 Fix exception with empty IF ELSE END-IF in a procedure
  TypeCobol.Test/Parser/Programs/Cobol85/WarningEndAlignment.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/WarningEndAlignment.rdzPGM.txt
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: Bug, To merge, TypeCobol, good first issue, 🔍 Ready for Review

#1689 1679 remove unused dependencies rebase1
  BuildScript.bat
  CLI/src/CLI.cs
  CLI/src/CLI.csproj
  CLI/src/Daemon.cs
  CLI/src/packages.config
  CLI/test/CLI.Test.csproj
  Codegen/src/Actions/Create.cs
  Codegen/src/Actions/CreateCode.cs
  Codegen/src/Actions/Replace.cs
  Codegen/src/Actions/ReplaceCode.cs
  Codegen/src/App.cs
  Codegen/src/Codegen.csproj
  Codegen/src/Config/ConfigParser.cs
  Codegen/src/Config/XmlParser.cs
  Codegen/src/Contribution/GlobalStorage.cs
  Codegen/src/Generator.cs
  Codegen/src/GeneratorActions.cs
  Codegen/src/GeneratorFactory.cs
  Codegen/src/GeneratorFactoryManager.cs
  Codegen/src/Generators/DefaultGenerator.cs
  Codegen/src/Generators/DefaultGeneratorWithLineMap.cs
  Codegen/src/Generators/LinearNodeSourceCodeMapper.cs
  Codegen/src/Generators/MixedTransformGenerator.cs
  Codegen/src/Generators/NestedGenerator.cs
  Codegen/src/Generators/SignaturesGenerator.cs
  Codegen/src/Generators/TypeCobolGenerator.cs
  Codegen/src/Nodes/FunctionDeclarationCG.cs
  Codegen/src/Nodes/Generated.cs
  Codegen/src/Skeletons/Condition.cs
  Codegen/src/Skeletons/Pattern.cs
  Codegen/src/Skeletons/Skeleton.cs
  Codegen/src/Skeletons/Skeleton.xsd
  Codegen/src/Skeletons/Templates/Eraser.cs
  Codegen/src/Skeletons/Templates/RazorEngine.cs
  Codegen/src/Skeletons/Templates/Solver.cs
  Codegen/src/Skeletons/skeletons.xml
  Codegen/src/packages.config
  Codegen/test/Codegen.Test.csproj
  Codegen/test/CodegenTestUtils.cs
  Codegen/test/Performance.cs
  Codegen/test/Razor.cs
  Codegen/test/TestCob85Codegen.cs
  Codegen/test/TestTypeCobolCodegen.cs
  TypeCobol.LanguageServer/JsonRPC/JsonRPCServer.cs
  TypeCobol.LanguageServer/TypeCobol.LanguageServer.csproj
  TypeCobol.Test/GrammarTest.cs
  TypeCobol.Test/Misc/QualifiedName.cs
  TypeCobol.Test/TypeCobol.Test.csproj
  TypeCobol.Test/packages.config
  TypeCobol.sln
  TypeCobol/Compiler/CodeElements/Expressions/FormalizedCommentDocumentation.cs
  TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs
  TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs
  TypeCobol/Compiler/Nodes/Documentation.cs
  TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
  TypeCobol/TypeCobol.csproj
  TypeCobol/packages.config
  build/package.py
Labels: 🔍 Ready for Review

#1694 WI #1678 New -ie|inputencoding option
  CLI/src/Daemon.cs
  CLI/test/CLITest.cs
  CLI/test/ressources/arguments_errors_1/CLIArguments.txt
  CLI/test/ressources/arguments_errors_1/ExpectedConsole.txt
  CLI/test/ressources/arguments_errors_2/ExpectedConsole.txt
  CLI/test/ressources/rdzformat_inputencoding_good/CLIArguments.txt
  CLI/test/ressources/rdzformat_inputencoding_good/input/test.tcbl
  CLI/test/ressources/rdzformat_inputencoding_good/output_expected/errors.txt
  CLI/test/ressources/rdzformat_inputencoding_good/output_expected/result.cbl
  CLI/test/ressources/rdzformat_inputencoding_wrong/CLIArguments.txt
  CLI/test/ressources/rdzformat_inputencoding_wrong/input/test.tcbl
  CLI/test/ressources/rdzformat_inputencoding_wrong/output_expected/errors.txt
  CLI/test/ressources/rdzformat_inputencoding_wrong/output_expected/result.cbl
  TypeCobol/Compiler/DocumentFormat.cs
  TypeCobol/Tools/Options-Config/TypeCobolConfiguration.cs
Labels: To merge, 🔍 Ready for Review

#1696 WI #1690 index not referenced
  TypeCobol.Test/Parser/Programs/TypeCobol/IndexTesting.rdz.tcbl
  TypeCobol.Test/Parser/Programs/TypeCobol/IndexTesting.rdzPGM.txt
  TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs
Labels: 🔍 Ready for Review
