Repository TypeCobolTeam/TypeCobol, pull requests merged in 2021-01, with the labels that each got.

#1838 WI #1837 Add Violation class
  TypeCobol/Analysis/Violation.cs
  TypeCobol/Compiler/CodeElements/ASTAnalyzerBase.cs
  TypeCobol/Compiler/CupParser/NodeBuilder/SyntaxDrivenAnalyzerBase.cs
  TypeCobol/Compiler/Diagnostics/Diagnostic.cs
  TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs
  TypeCobol/Compiler/Diagnostics/MessageCode.cs
  TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
Labels: Enhancement

#1719 WI #1676 Allow empty IF/ELSE constructs in Cup grammar
  TypeCobol.LanguageServer.Test/LSRTests/IfCompletion/input/IfCompletion.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionPotentialChildrenWithNoName/input/ProcedureCompletionPotentialChildrenWithNoName.tlsp
  TypeCobol.Test/Parser/Programs/Cobol85/IfStatements.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/IfStatements.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/WarningEndAlignment.rdzPGM.txt
  TypeCobol/Compiler/CupParser/TypeCobolProgram.cup
  TypeCobol/Compiler/CupParser/TypeCobolProgramParser.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: 🔍 Ready for Review

#1857 WI #428 Handle token scan state dependent in DataDivision.
  TypeCobol.Test/Parser/Programs/Cobol85/ReplaceTokenInsideDataDiv2.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/ReplaceTokenInsideDataDiv2.rdzSYM.txt
  TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs
  TypeCobol/Compiler/Scanner/ITokensLine.cs
  TypeCobol/Compiler/Scanner/Scanner.cs
  TypeCobol/Compiler/Scanner/Token.cs
Labels: Bug, Cobol, TypeCobol

#1855 1808 report missing copies all levels ptd rebase
  CLI/test/CLITest.cs
  CLI/test/ressources/checkMissingCopies_2/CLIArguments.txt
  CLI/test/ressources/checkMissingCopies_2/input/Copies/COPY1.CPY
  CLI/test/ressources/checkMissingCopies_2/input/Copies/COPY2.CPY
  CLI/test/ressources/checkMissingCopies_2/input/MissingCopy.rdz.tcbl
  CLI/test/ressources/checkMissingCopies_2/output_expected/MissingCopy.txt
  CLI/test/ressources/checkMissingCopies_2/output_expected/error.txt
  TypeCobol.LanguageServer/Workspace.cs
  TypeCobol.Test/Parser/Preprocessor/CopyResultFiles/PgmCopy.txt
  TypeCobol/Analysis/Violation.cs
  TypeCobol/Compiler/CompilationDocument.cs
  TypeCobol/Compiler/Diagnostics/Diagnostic.cs
  TypeCobol/Compiler/Diagnostics/DiagnosticMessage.cs
  TypeCobol/Compiler/Diagnostics/MessageCode.cs
  TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
  TypeCobol/Compiler/Preprocessor/MissingCopy.cs
  TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
  TypeCobol/Compiler/Preprocessor/ProcessedTokensDocument.cs
  TypeCobol/Parser.cs
  TypeCobol/Tools/APIHelpers/Helpers.cs
Labels: Cobol, Enhancement, User Visible

#1856 WI #1852 Avoid exception in DataDescriptionChecker on multiple VALUE …
  CLI/test/CLITest.cs
  CLI/test/ressources/CopyBrokenFormat/CLIArguments.txt
  CLI/test/ressources/CopyBrokenFormat/input/COMPCOPY.pgm
  CLI/test/ressources/CopyBrokenFormat/input/Copies/YBRKCPY.cpy
  CLI/test/ressources/CopyBrokenFormat/output_expected/error.txt
  TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
Labels: Bug

#1850 WI #1834 Target .NET framework 4.7.2
  Analytics/packages.config
  CLI/test/CLI.Test.csproj
  CSCup/App.config
  Codegen/src/App.config
  Codegen/src/Codegen.csproj
  Codegen/src/packages.config
  Codegen/test/Codegen.Test.csproj
  TypeCobol.Analysis/packages.config
  TypeCobol.LanguageServer.Test/TypeCobol.LanguageServer.Test.csproj
  TypeCobol.LanguageServer.Test/packages.config
  TypeCobol.LanguageServer/App.config
  TypeCobol.LanguageServer/packages.config
  TypeCobol.Test/TypeCobol.Test.csproj
  TypeCobol.Test/packages.config
  TypeCobol.Transform.Test/TypeCobol.Transform.Test.csproj
  TypeCobol.Transform/App.config
  TypeCobol/Common.props
  TypeCobol/packages.config
Labels: To merge

#1867 WI #1864 Add peformance test with CFG/DFA
  TypeCobol.Analysis.Test/PerformanceWithCfg.cs
  TypeCobol.Analysis.Test/PerformanceWithCfgDfa.cs
  TypeCobol.Analysis.Test/TypeCobol.Analysis.Test.csproj
  TypeCobol.Test/Parser/Performance/Performance.cs
Labels: DataFlow, Performance, Tests, TypeCobol

#1871 WI #1869 Remove IASTAnalyzer, use QualityAnalyzer concept instead
  CLI/test/ressources/custom_analyzers/output_expected/errors.txt
  TypeCobol.Analysis.Test/CustomAnalyzers/Analyzers.cs
  TypeCobol.Analysis.Test/CustomAnalyzers/TestAnalyzerProvider.cs
  TypeCobol/Analysis/AnalyzerProvider.cs
  TypeCobol/Analysis/IASTAnalyzer.cs
  TypeCobol/Analysis/IAnalyzerProvider.cs
  TypeCobol/Analysis/IQualityAnalyzer.cs
  TypeCobol/Analysis/QualityAnalyzerBase.cs
  TypeCobol/Compiler/CodeElements/ASTAnalyzerBase.cs
  TypeCobol/Compiler/CompilationUnit.cs
  TypeCobol/Compiler/Parser/ProgramClassDocument.cs
Labels: To merge
