Repository TypeCobolTeam/TypeCobol, pull requests merged in 2021-09, with the labels that each got.

#2034 WI #1847 secure external analyzers
  CLI/src/CLI.cs
  CLI/test/CLITest.cs
  CLI/test/ressources/custom_analyzers/output_expected/errors.txt
  CLI/test/ressources/custom_analyzers_withcfg/output_expected/errors.txt
  TypeCobol.Analysis.Test/CfgTestUtils.cs
  TypeCobol.Analysis.Test/CustomAnalyzers/Analyzers.cs
  TypeCobol.Analysis.Test/CustomAnalyzers/TestAnalyzerProvider.cs
  TypeCobol.Analysis.Test/PerformanceWithCfg.cs
  TypeCobol.Analysis.Test/PerformanceWithCfgDfa.cs
  TypeCobol.LanguageServer/Workspace.cs
  TypeCobol.Test/Report/ReportTestHelper.cs
  TypeCobol/Analysis/AnalyzerProvider.cs
  TypeCobol/Analysis/AnalyzerProviderLoader.cs
  TypeCobol/Analysis/AnalyzerProviderWrapper.cs
  TypeCobol/Compiler/CompilationUnit.cs
Labels: Security, QualityCheck

#2036 WI #1846 multi line diagnostics
  CLI/src/CLI.cs
  CLI/src/Writer.cs
  CLI/test/ressources/dependenciesNotLoadedInCorrectOrder/output_expected/error.txt
  CLI/test/ressources/dependencies_3/output_expected/error.txt
  CLI/test/ressources/ei_dependencies_1/output_expected/error.txt
  Codegen/src/Generators/DefaultGenerator.cs
  TypeCobol.Analysis.Test/BasicCfgInstrs/CGM110.diag
  TypeCobol.LanguageServer.Test/LSRTests/GlobalStorageCompletion/input/GlobalStorageCompletion.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/OnHover/input/OnHover.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/OutlineRefresh/input/OutlineRefresh.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionCaseInsensitive/input/ProcedureCompletionCaseInsensitive.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionInputInoutOutput-Case/input/ProcedureCompletionInputInoutOutput-Case.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionInputInoutOutput-NoContext/input/ProcedureCompletionInputInoutOutput-NoContext.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionInputInoutOutput/input/ProcedureCompletionInputInoutOutput.tlsp
  TypeCobol.LanguageServer/TypeCobolServer.cs
  TypeCobol.Test/Misc/LanguageLevel/tcCall.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/BlockContains.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/DebugLinesWithDebugging.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndDisorder.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndDisorderNoName.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndMissingEndLastStackedWithNested.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndMissingMain.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndMissingNested0.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ProgramEndMissingNested1.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhen.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhen2.rdzMix.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/LibraryFunction.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/Omitted.rdzMix.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-PublicPrivate.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-PublicPrivate.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-overload.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-public.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall-public.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/ProcedureCall.rdzPGM.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/TCRFUN_NO_COPY_IN_PARAMETERS.rdzPGM-EI.txt
  TypeCobol.Test/Parser/Programs/TypeCobol/TCRFUN_NO_COPY_IN_PARAMETERS.rdzPGM.txt
  TypeCobol.Test/Utils/Comparator.cs
  TypeCobol.Test/Utils/ParserUtils.cs
  TypeCobol/Compiler/CodeElements/CodeElement.cs
  TypeCobol/Compiler/CompilationDocument.cs
  TypeCobol/Compiler/Diagnostics/Diagnostic.cs
  TypeCobol/Compiler/Parser/CodeElementsLine.cs
  TypeCobol/Compiler/Parser/CodeElementsParserStep.cs
  TypeCobol/Compiler/Parser/DiagnosticUtils.cs
  TypeCobol/Compiler/Preprocessor/PreprocessorStep.cs
  TypeCobol/Compiler/Scanner/TokensLine.cs
  TypeCobol/Compiler/Text/CobolTextLine.cs
  TypeCobol/Compiler/Text/ITextLine.cs
Labels: Enhancement, CLI, Language Server Protocol

#2030 WI #2026 #2027 Avoid FileCompiler leaks in LanguageServer
  TypeCobol.LanguageServer.Test/LSRTests/ProcedureCompletionNoParam/input/ProcedureCompletionNoParam.tlsp
  TypeCobol.LanguageServer/Workspace.cs
  TypeCobol.Test/Parser/Preprocessor/PreprocessorUtils.cs
  TypeCobol/Compiler/AntlrUtils/AntlrPerformanceProfiler.cs
  TypeCobol/Compiler/AntlrUtils/TokensLinesTokenStream.cs
  TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs
  TypeCobol/Compiler/Parser/CodeElementsLinesTokenSource.cs
  TypeCobol/Compiler/Preprocessor/CopyTokensLinesIterator.cs
  TypeCobol/Compiler/Scanner/ITokensLinesIterator.cs
  TypeCobol/Compiler/Scanner/Token.cs
  TypeCobol/Compiler/Scanner/TokensLinesIterator.cs
  TypeCobol/LanguageServices/CodeAnalysis/Statistics/StatsGenerator.cs
Labels: 🔍 Ready for Review

#2024 2022 abstract int multi branch context
  TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.BasicBlockForNodeGroup.cs
  TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.CfgAfterIterativePerformProcedureTransformer.cs
  TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.MultiBranchContext.cs
  TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.cs
  TypeCobol.Analysis/Graph/BasicBlock.cs
  TypeCobol.Analysis/Graph/ControlFlowGraph.cs
  TypeCobol.Analysis/Graph/IMultiBranchContext.cs
  TypeCobol.Analysis/TypeCobol.Analysis.csproj
Labels: DataFlow
