Repository TypeCobolTeam/TypeCobol, pull requests merged in 2022-02, with the labels that each got.

#2131 1874 new diag conf section in nested program
  TypeCobol.Test/Parser/Programs/Cobol85/NoConfSectionInNestedPrg.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/NoConfSectionInNestedPrg.rdzMix.txt
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: Error

#2135 WI #2044 Check usage of common and recursive attributes
  TypeCobol.Test/Parser/Programs/Cobol85/CommonProgramAttributes.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/CommonProgramAttributes.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/RecursiveProgramAttributes.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/RecursiveProgramAttributes.rdzMix.txt
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: 🔍 Ready for Review

#2134 2125 fix null reference exception
  TypeCobol.Test/Parser/Programs/Cobol85/EmptySearchStatement.rdz-Nodes.txt
  TypeCobol.Test/Parser/Programs/Cobol85/EmptySearchStatement.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTest.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTestNoEndEvaluate.rdzMix.txt
  TypeCobol/Compiler/CupParser/EmptyTypeCobolProgram.cup
  TypeCobol/Compiler/CupParser/TypeCobolProgram.cup
  TypeCobol/Compiler/CupParser/TypeCobolProgramParser.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: 🔍 Ready for Review

#2115 WI #2069 Add check for condition names, and special check for level 88 data definitions.
  TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhenLevel88.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/SearchAllWhenLevel88.rdzMix.txt
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: Bug, Cobol, 🔍 Ready for Review
