Repository TypeCobolTeam/TypeCobol, pull requests merged in 2022-01, with the labels that each got.

#2094 WI #2083 Allow the syntax of abbreviated expression
  TypeCobol.Test/Parser/Programs/Cobol85/AbbrevExprression.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/AbbrevExprression.rdzPGM.txt
  TypeCobol/AntlrGrammar/CobolExpressions.g4
  TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs
Labels: Bug, 🔍 Ready for Review

#2102 WI #2101 Use ANTLR C# code generator .NET implementation instead of Java
  TypeCobol/TypeCobol.csproj
Labels: 🔍 Ready for Review

#2074 WI #2064 store all tokens channels in pseudo texts.
  TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Copy.txt
  TypeCobol.Test/Parser/Preprocessor/DirectiveResultFiles/Replace.txt
  TypeCobol.Test/Parser/Preprocessor/ReplaceResultFiles/PgmReplaceFunction.txt
  TypeCobol.Test/Parser/Preprocessor/ReplaceResultFiles/PgmReplaceSingleToMultiple.txt
  TypeCobol.Test/Parser/Programs/Cobol85/ReplaceMultipleTokens.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/ReplaceMultipleTokens.rdzSYM.txt
  TypeCobol/Compiler/CupCommon/CobolWordsTokenizer.cs
  TypeCobol/Compiler/CupPreprocessor/CobolCompilerDirectives.cup
  TypeCobol/Compiler/CupPreprocessor/CobolCompilerDirectivesParser.cs
  TypeCobol/Compiler/Preprocessor/ReplaceTokensLinesIterator.cs
  TypeCobol/Compiler/Scanner/Scanner.cs
  TypeCobol/Compiler/Scanner/ScannerUtils.cs
  TypeCobol/Compiler/Scanner/Token.cs
  TypeCobol/Compiler/Scanner/TokensGroup.cs
  TypeCobol/Compiler/Text/CobolTextLine.cs
Labels: Bug, Cobol, 🔍 Ready for Review

#2085 WI #2068 Support Multi strings in continuation lines
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationMultiStrings.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/ContinuationMultiStrings.rdzMix.txt
  TypeCobol.Test/Parser/Scanner/ResultFiles/AlphanumericLiterals-continuations.txt
  TypeCobol/Compiler/Diagnostics/Resources/DiagnosticMessages.csv
  TypeCobol/Compiler/Scanner/ContinuationToken.cs
  TypeCobol/Compiler/Scanner/Scanner.cs
  TypeCobol/Compiler/Text/CobolFormatAreas.cs
Labels: Bug, 🔍 Ready for Review

#2073 WI #1593 Use whenCondition with no expression
  TypeCobol.LanguageServer.Test/LSRTest.cs
  TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterWhen/input/CompletionAfterWhen.tlsp
  TypeCobol.LanguageServer.Test/LSRTests/CompletionAfterWhen/output_expected/CompletionAfterWhen.rlsp
  TypeCobol.LanguageServer/Completion Factory/CompletionFactoryHelpers.cs
  TypeCobol.Test/Parser/Programs/Cobol85/MultipleWhenWithoutStatementsPGM.txt
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTest.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTest.rdzMix.txt
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTestNoEndEvaluate.rdz.cbl
  TypeCobol.Test/Parser/Programs/Cobol85/WhenTestNoEndEvaluate.rdzMix.txt
  TypeCobol/AntlrGrammar/CobolCodeElements.g4
  TypeCobol/Compiler/CupParser/TypeCobolProgram.cup
  TypeCobol/Compiler/CupParser/TypeCobolProgramParser.cs
  TypeCobol/Compiler/Diagnostics/CodeElementCheckers.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
  TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
  TypeCobol/Compiler/Parser/CodeElementBuilder/CobolStatementsBuilder.cs
  TypeCobol/TypeCobol.csproj
Labels: Cobol, Language Server Protocol, 🔍 Ready for Review

#2098 WI #1880 Use Semantic data to optimize CrossChecker.CheckParagraph
  TypeCobol/Compiler/CodeModel/SymbolTable.cs
  TypeCobol/Compiler/Diagnostics/CrossChecker.cs
Labels: Performance, 🔍 Ready for Review
